// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    coinflip_hack
    (
        init => init
        hack_coinflip => hack_coinflip
        donate_after_win => donate_after_win
        set_donation_wallet => set_donation_wallet
        verify_contract_connection => verify_contract_connection
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
